import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    "Search": "Search",
    "Error": "Error",
    "Close": "Close",
    "Warning": "Warning",
    "Search origin address...": "Search origin address...",
    "Search destiny address...": "Search destiny address...",
    "Please check your internet connection.": "Please check your internet connection.",
    "Create Ride": "Create Ride",
    "Rides": "Rides",
    "Driver": "Driver",
    "Cars": "Cars",
    "Call Center": "Call Center",
    "Log Out": "Log Out",
    "Origin": "Origin",
    "Destiny": "Destiny",
    "No results for": "No results for {0}",
    "No rides found": "No rides found",
    "New Ride": "New Ride",
    "Mark as Unavailable": "Mark as Unavailable",
    "'You are not registered as a driver.'": "'You are not registered as a driver.'",
    "This device is not registered as a car.": "This device is not registered as a car.",
    "Start Ride": "Start",
    "Forget Ride": "Cancel",
    "Ride Finished": "Finished",
    "Make Ride": "Make Ride",
    "Change Date/Time": "Change Date/Time",
    "No internet connection...": "No internet connection...",
    "Rate your ride.": "Rate your ride.",
    "Reminder": "Reminder",
    "Notification": "Notification",
    "Details": "Details",
    "Search for bookmarks": "Search for bookmarks",
    "Select Origin": "Select Origin",
    "Select Destiny": "Select Destiny",
    "No bookmarks available": "No bookmarks available",
    "Details": "Details",
    "Waiting": "Waiting",
    "Do it!": "Do it!",
    "Make this Ride": "Make this Ride",
    "Notify": "Notify",
    "Leave": "Leave",
    "Update Ride": "Update Ride",
    "Leave this Ride": "Leave this Ride",
    "Mark this ride as started.": "Mark this ride as started.",
    "Mark this ride as finished.": "Mark this ride as finished.",
    "Tell passengers that I am waiting.": "Tell passengers that I am waiting.",
    "Ride starts in": "Ride starts in {0} minutes.",
    "Ride attributed to you.": "Ride attributed to you.",
    "You were removed from a ride.": "You were removed from a ride.",
    "New passenger in your ride.": "{0} will ride with you.",
    "A car was attributed to your ride.": "{0} was attributed to your ride.",
    "New ride need a car.": "New ride need a car.",
    "Car has arrived and is waiting.": "{0} has arrived and is waiting.",
    "\nThere seams to be a problem with the server.\n\n Please wait a few minutes and try again.": "\nThere seams to be a problem with the server.\n\n Please wait a few minutes and try again.",
    "Retry!": "Retry!",
    "Unanthorized": "Unanthorized"
  },
  pt: {
    "Search": "Procurar",
    "Error": "Erro",
    "Close": "Fechar",
    "Warning": "Aviso",
    "Search origin address...": "Procurar endereço de origem...",
    "Search destiny address...": "Procurar endereço de destino...",
    "Please check your internet connection.": "Verifica a conexão à internet.",
    "Create Ride": "Criar Boleia",
    "Rides": "Boleias",
    "Driver": "Driver",
    "Cars": "Carro",
    "Call Center": "CDO",
    "Log Out": "Log Out",
    "Origin": "Origem",
    "Destiny": "Destino",
    "No results for": "Não há resultados para {0}",
    "No rides found": "Não há boleias",
    "New Ride": "Nova Boleia",
    "Mark as Unavailable": "Marcar como Não Disponível",
    "'You are not registered as a driver.'": "'Não está registado como Driver.'",
    "This device is not registered as a car.": "Este equipamento não está registado como Carro.",
    "Start Ride": "Iniciar",
    "Forget Ride": "Cancelar",
    "Ride Finished": "Terminar",
    "Make Ride": "Aceitar Boleia",
    "Change Date/Time": "Alterar Hora/Data",
    "No internet connection...": "Sem Internet...",
    "Rate your ride.": "Classifica a boleia.",
    "Reminder": "Lembrete",
    "Notification": "Notificação",
    "Details": "Detalhes",
    "Search for bookmarks": "Procurar favoritos",
    "Select Origin": "Selecionar Origem",
    "Select Destiny": "Selecionar Destino",
    "No bookmarks available": "Sem favoritos",
    "Details": "Detalhes",
    "Waiting": "À espera",
    "Do it!": "Aceitar",
    "Make this Ride": "Aceitar Boleia",
    "Notify": "Notificar",
    "Leave": "Cancelar",
    "Update Ride": "Atualizar Boleia",
    "Leave this Ride": "Cancelar Boleia ",
    "Mark this ride as started.": "Marcar boleia como iniciada.",
    "Mark this ride as finished.": "Marcar boleia como terminada.",
    "Tell passengers that I am waiting.": "Dizer que estou à espera.",
    "Ride starts in": "Boleia em {0} minutos.",
    "Ride attributed to you.": "Nova boleia atribuída.",
    "You were removed from a ride.": "Foi removido de uma boleia.",
    "New passenger in your ride.": "{0} colou-se à tua boleia.",
    "A car was attributed to your ride.": "{0} aceitou a tua boleia.",
    "New ride need a car.": "Nova boleia precisa de carro.",
    "Car has arrived and is waiting.": "{0} já chegou e está à espera."
  }
});

export default strings;